### ISSUE TITLE
OpaResponse deserilization fails if the JSON response contains unexpected fields

### ISSUE THREAD

**Issue by maltesander** [stackabletech/druid-opa-authorizer#72]
The OpaResponse object currently only expects a `result` field when deserializing: https://github.com/stackabletech/druid-opa-authorizer/blob/main/src/main/java/tech/stackable/druid/opaauthorizer/opatypes/OpaResponse.java

When e.g. enabling decision logging in OPA, this will add at least another field `decision_id` to the JSON response and therefore running into an exception when deserializing.

See https://github.com/stackabletech/opa-operator/issues/422

**Comment by lfrancke** [comment]
@maltesander it looks like this bug has actually been fixed?

**Comment by maltesander** [comment]
Yes fixed. Closing.
